version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: '10.1.1.53'
    container_name: hussein-gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://hussein.sne.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
