stages:
  - build
  - test
  - release
  - deploy
# update deploy stage #9
variables:
  CONTAINER_COMPOSE_IMAGE: hello_djangoapp
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  image: docker:latest
  stage: build
  before_script:
    - docker login -u ha33ona -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker tag $CONTAINER_TEST_IMAGE ha33ona/$CONTAINER_TEST_IMAGE
    - docker push ha33ona/$CONTAINER_TEST_IMAGE
  tags:
    - hussein-runner

unit_test:
  image: docker:latest
  stage: test
  script:
    - docker pull ha33ona/$CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_COMPOSE_IMAGE
    - make test
    - echo $SUDO_PASS | sudo -S rm -rf .tox
    - echo $SUDO_PASS | sudo -S rm -rf __pycache__
    - echo $SUDO_PASS | sudo -S rm -rf hello.egg-info
    - echo $SUDO_PASS | sudo -S rm -rf hello
    - echo $SUDO_PASS | sudo -S rm -rf tests
    - pwd
    - ls -la

  tags:
    - hussein-runner

release-image:
  image: docker:latest
  stage: release
  before_script:
    - docker login -u ha33ona -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull ha33ona/$CONTAINER_TEST_IMAGE
    - docker tag ha33ona/$CONTAINER_TEST_IMAGE ha33ona/$CONTAINER_RELEASE_IMAGE
    - docker push ha33ona/$CONTAINER_RELEASE_IMAGE
  only:
    - main
  tags:
    - hussein-runner

deploy-staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: http://staging.hussein.com
  only:
    - main
  tags:
    - hussein-runner

deploy-prod:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no hussein@10.1.1.56 "
        docker login -u ha33ona -p $CI_JOB_TOKEN $CI_REGISTRY &&
        git clone http://gitlab-ci-tokne:$REPO_TOKEN@hussein.sne.com/gitlab-instance-610d8aec/hussein-repo.git &&
        ls &&
        cd hussein-repo &&
        docker-compose up -d"
  only:
    - main
  tags:
    - hussein-runner
